# Generated by Django 4.2.7 on 2023-12-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('channel', models.CharField(max_length=255)),
                ('views', models.CharField(max_length=100)),
                ('user', models.ImageField(blank=True, null=True, upload_to='user/')),
            ],
        ),
    ]
